// <auto-generated />
using System;
using System.Collections.Generic;
using Inventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inventory.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106132841_add_inbox")]
    partial class add_inbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Inventory.Domain.Entities.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("event_type");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_on_utc");

                    b.Property<DateTimeOffset>("ReceivedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("received_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.InventoryHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.HasKey("Id");

                    b.ToTable("inventory_histories", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.InventoryItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int>("Reserved")
                        .HasColumnType("int")
                        .HasColumnName("reserved");

                    b.ComplexProperty<Dictionary<string, object>>("Product", "Inventory.Domain.Entities.InventoryItemEntity.Product#Product", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasMaxLength(50)
                                .HasColumnType("char(50)")
                                .HasColumnName("product_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("product_name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.InventoryReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified_on_utc");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("Product", "Inventory.Domain.Entities.InventoryReservationEntity.Product#Product", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id")
                                .HasMaxLength(50)
                                .HasColumnType("char(50)")
                                .HasColumnName("product_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("product_name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.ToTable("inventory_reservations", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.LocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("longtext")
                        .HasColumnName("last_error_message");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3)
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("NextAttemptOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("next_attempt_on_utc");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOnUtc");

                    b.HasIndex("ProcessedOnUtc");

                    b.HasIndex("NextAttemptOnUtc", "ProcessedOnUtc", "AttemptCount");

                    b.HasIndex("ProcessedOnUtc", "AttemptCount", "MaxAttempts");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Inventory.Domain.Entities.InventoryItemEntity", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Inventory.Domain.Entities.InventoryReservationEntity", b =>
                {
                    b.HasOne("Inventory.Domain.Entities.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
