# These are supported funding model platforms
community_bridge: ProG Coder Shop Microservices
github: [huynxtb]
buy_me_a_coffee: progcoder
custom: ["https://www.paypal.com/paypalme/huynx11?locale.x=vi_VN&country.x=VN"]