# CodeRabbit Configuration for ProG Coder Shop Microservices
# AI-powered code review configuration optimized for .NET 8 microservices with Clean Architecture

# Language-specific settings
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    github-checks:
      enabled: true
      timeout: 45

# Review focus areas
chat:
  auto_reply: true

# Path-specific instructions for different architectural layers
path_instructions:
  # Domain Layer - DDD patterns
  - path: "**/Domain/**/*.cs"
    instructions: |
      - Verify Domain-Driven Design principles: Entities, Value Objects, Aggregates, Domain Events
      - Check that domain logic is not leaking to other layers
      - Ensure entities maintain their invariants
      - Review aggregate boundaries and consistency rules
      - Validate domain event definitions and naming
      - Check for proper encapsulation of domain logic
      - Ensure no infrastructure dependencies

  # Application Layer - CQRS, MediatR, Commands/Queries
  - path: "**/Application/**/*.cs"
    instructions: |
      - Verify CQRS patterns: Commands modify state, Queries only read
      - Check MediatR command/query handler implementations
      - Validate FluentValidation rules for commands and queries
      - Review mapping between domain models and DTOs
      - Ensure proper use of Result pattern or exception handling
      - Check for proper dependency injection
      - Verify no direct database access (should use repositories)

  # Infrastructure Layer - EF Core, Repositories, External services
  - path: "**/Infrastructure/**/*.cs"
    instructions: |
      - Review Entity Framework Core configurations and DbContext setup
      - Check repository pattern implementations
      - Validate database queries for N+1 problems
      - Review proper use of async/await patterns
      - Check for SQL injection vulnerabilities
      - Verify connection string management and security
      - Review external service integrations (RabbitMQ, Redis, MinIO)
      - Check proper use of using statements for disposable resources

  # API Layer - Carter, REST endpoints, Minimal APIs
  - path: "**/Api/**/*.cs"
    instructions: |
      - Review REST API endpoint design and HTTP verb usage
      - Check proper status code returns (200, 201, 400, 404, 500)
      - Validate request/response DTOs and API contracts
      - Review authentication and authorization attributes
      - Check proper error handling and exception middleware
      - Verify API versioning if implemented
      - Review CORS configuration
      - Check health check endpoints

  # Database Migrations
  - path: "**/Migrations/**/*.cs"
    instructions: |
      - Review migration for breaking changes
      - Check for proper indexes on foreign keys and frequently queried columns
      - Verify data migration scripts if needed
      - Ensure backward compatibility if required
      - Check for proper rollback procedures

  # React Frontend - Components
  - path: "**/src/Apps/**/*.jsx"
    instructions: |
      - Review React hooks usage (useState, useEffect, useMemo, useCallback)
      - Check for prop-types or TypeScript type definitions
      - Verify proper component composition and reusability
      - Review state management approach
      - Check for performance issues (unnecessary re-renders)
      - Validate accessibility (a11y) attributes
      - Review error boundary implementations

  # React Frontend - Hooks
  - path: "**/src/Apps/**/hooks/**/*.js"
    instructions: |
      - Review custom hooks for proper dependencies in useEffect
      - Check for proper cleanup in useEffect return functions
      - Verify hooks follow naming convention (useXxx)
      - Check for potential infinite loops or memory leaks

  # Docker Configuration
  - path: "**/Dockerfile"
    instructions: |
      - Review multi-stage build optimization
      - Check for security vulnerabilities (running as root, exposed secrets)
      - Verify proper layer caching strategy
      - Check base image selection and version pinning
      - Review EXPOSE port configurations
      - Verify proper use of .dockerignore

  # Docker Compose
  - path: "**/docker-compose*.yml"
    instructions: |
      - Review service dependencies and startup order
      - Check environment variable management
      - Verify volume mounts and data persistence
      - Review network configuration
      - Check health checks configuration
      - Verify resource limits (CPU, memory)

  # Worker Services - Background Jobs, Outbox Pattern
  - path: "**/Worker/**/*.cs"
    instructions: |
      - Review background job implementations
      - Check Outbox pattern implementation for reliable event publishing
      - Verify proper error handling and retry logic
      - Review job scheduling and concurrency
      - Check for proper cancellation token usage
      - Verify logging and monitoring

  # Event Handlers - MassTransit Consumers
  - path: "**/Consumers/**/*.cs"
    instructions: |
      - Review MassTransit consumer implementations
      - Check idempotency handling for message processing
      - Verify proper error handling and retry policies
      - Review message validation
      - Check for proper saga state management if applicable
      - Verify dead-letter queue configuration

  # Configuration files
  - path: "**/appsettings*.json"
    instructions: |
      - Check for hardcoded secrets (should use environment variables or key vault)
      - Review connection string configurations
      - Verify logging level settings
      - Check CORS and authentication configurations

  # Tests
  - path: "**/Tests/**/*.cs"
    instructions: |
      - Review test coverage and edge cases
      - Check test naming conventions (method_scenario_expectedResult)
      - Verify proper use of mocking and test doubles
      - Review test data setup and cleanup
      - Check for flaky tests or test dependencies
      - Verify integration test configurations

# Files and patterns to ignore
reviews:
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "work in progress"

# Exclude patterns - files that should not be reviewed
path_filters:
  excluded:
    # Generated files
    - "**/Migrations/**"
    - "**/obj/**"
    - "**/bin/**"
    - "**/*.Designer.cs"
    - "**/*Generated*.cs"
    
    # Dependencies
    - "**/node_modules/**"
    - "**/package-lock.json"
    - "**/yarn.lock"
    - "**/pnpm-lock.yaml"
    
    # Build artifacts
    - "**/dist/**"
    - "**/build/**"
    - "**/out/**"
    
    # Local data and volumes
    - "**/local-data/**"
    - "**/docker-volumes/**"
    
    # IDE and OS files
    - "**/.vs/**"
    - "**/.vscode/**"
    - "**/.idea/**"
    - "**/*.suo"
    - "**/*.user"
    - "**/.DS_Store"
    
    # Logs and temp files
    - "**/*.log"
    - "**/*.tmp"
    
    # Assets and media
    - "**/*.png"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.gif"
    - "**/*.svg"
    - "**/*.ico"
    - "**/*.woff"
    - "**/*.woff2"
    - "**/*.ttf"
    - "**/*.eot"
    
    # Documentation (optional - remove if you want to review docs)
    - "**/*.md"
    
    # Test data
    - "**/TestData/**"
    - "**/test-data/**"

  included:
    - "**/*.cs"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.json"
    - "**/*.yaml"
    - "**/*.yml"
    - "**/Dockerfile"
    - "**/*.csproj"

# Security-focused checks
security:
  enabled: true

# Performance optimization checks  
performance:
  enabled: true

# Custom review prompts for specific concerns
knowledge_base:
  enabled: true
  learnings:
    - "This project follows Clean Architecture with Domain, Application, Infrastructure, and API layers"
    - "CQRS pattern is used: Commands modify state, Queries only read data"
    - "MediatR handles command and query dispatching"
    - "FluentValidation is used for input validation"
    - "Event-driven architecture with RabbitMQ and MassTransit"
    - "Outbox pattern ensures reliable event publishing"
    - "Entity Framework Core is the primary ORM"
    - "Carter is used for minimal API endpoints"
    - "Keycloak handles authentication and authorization"
    - "Redis is used for caching and session management"
    - "MinIO stores product images and files"
    - "Elasticsearch powers the search functionality"
    - "OpenTelemetry, Prometheus, and Grafana for observability"
    - "Serilog for structured logging"
    - "Follow Conventional Commits specification for commit messages"
    - "Services communicate via gRPC (sync) and RabbitMQ (async)"

# Review tone and style
tone_instructions: |
  - Be constructive and educational
  - Explain the "why" behind suggestions
  - Provide code examples when helpful
  - Reference SOLID principles and design patterns
  - Consider microservices best practices
  - Focus on security, performance, architecture, and code quality
  - Be specific about potential issues and their impact
  - Suggest concrete improvements with rationale







