# CodeRabbit Configuration for ProG Coder Shop Microservices
# AI-powered code review configuration optimized for .NET 8 microservices with Clean Architecture

# Language-specific settings
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
      - "work in progress"
  tools:
    github-checks:
      enabled: true
      timeout: 45

# Review focus areas
chat:
  auto_reply: true

# Custom review prompts for specific concerns
knowledge_base:
  enabled: true
  learnings:
    architecture: "Clean Architecture with Domain, Application, Infrastructure, and API layers"
    patterns: "CQRS with MediatR, Outbox pattern, Event-driven with RabbitMQ"
    stack: ".NET 8, EF Core, Carter, FluentValidation, Keycloak, Redis, MinIO, Elasticsearch"
    observability: "OpenTelemetry, Prometheus, Grafana, Serilog"
    communication: "gRPC for sync, RabbitMQ for async"

# Review tone and style
tone_instructions: "Be constructive, explain rationale, provide examples, reference SOLID principles, focus on security, performance, and architecture"
