global using BuildingBlocks.CQRS;
global using FluentValidation;
global using Common.Models;
global using Common.Constants;
global using Common.Extensions;
global using Mapster;
global using BuildingBlocks.Pagination;
global using BuildingBlocks.Exceptions;
global using BuildingBlocks.Abstractions.ValueObjects;